### ISSUE TITLE
packit-service-validation: check both stg and prod

### ISSUE THREAD

**Issue by TomasTomecek** [packit/deployment#318]
With the more granular split of prod and stg, we can now better pinpoint jobs and `/packit[-stg]` comments to specific deployments.

At the same time, the validation script did not account for the stg deployment.

This issue tracks work so that the validation script can check both prod and stg (design and implementation are open).

This will give us daily update about the status of the stg deployment - we can be aware of problems in stg faster.

We should be able to define which test cases are triggered against both deployments to not overload the infra.

Please comment if you disagree or have ideas about stg validation.

Refinement notes:
- create a new cron job
- make the cron job configurable

**Comment by majamassarini** [comment]
As far as I can understand we test 3 different trigger types and for each of them the work to do is slightly different

- **commit trigger**: this is *already being tested both for staging and production* instances. 
As it is right now it could not be run by different cron jobs for `prod` and `stg`. If we want to have different cron jobs for `prod` and `stage`, for this kind of test, we need:
- [ ] to create a new always opened PR and fix the yaml files for the old one and the new one so that one runs using `stg` instance and the other one runs using the `prod` instance.

- **comment trigger**: there are a lot of tests of this kind which, until now, run just on the *production instance*. To make them run both on `prod` and `stg`:
- [ ] the `packit-service-validation.py` script should be enhanced to *differentiate making comments* using `/packit build` or `/packit-stg build`

- **push trigger**: these test runs just on the *production instance*
- [ ] Create another branch like `test_case_opened_pr` branch where the yaml file is modified to work on the `stg` instance.

---

- [ ] When all the above points are done, the `packit-service-validation.py` script should be further enhanced to differentiate between tests for `prod` and `stg` instances and then we can call it from a brand new cron job meant to test just the staging instance.

**Comment by TomasTomecek** [comment]
* commit trigger - if this is already tested, then I'd say we're fine and don't need to create a new mechanism here
* comment trigger - +1, do we have a list of test cases - should we run all of them for both deployments or cherry-pick?
* push trigger - agreed that we can do pushes to a separate branch, but we could also handle one push job so both deployments react: would that work? https://packit.dev/docs/configuration/#packit_instances

**Comment by lbarcziova** [comment]
From my perspective, for the opened PR trigger and push trigger, the code doesn't need to be changed much, only new branches should be created so that the staging is configured for these branches and they should be used in the code. As for the comment trigger, +1, this is only about differentiating the comments. And one things that need to be changed in general is making the app name [here](https://github.com/packit/deployment/blob/ac058d2e663e8e7d6886be1b9547a65796e02d68/cron-jobs/packit-service-validation/packit-service-validation.py#L20) configurable - this is used when checking the commit checks.
