### ISSUE TITLE
Research deployment methodologies

### ISSUE THREAD

**Issue by TomasTomecek** [packit/deployment#382]
Research different ways we could deploy our projects. Focus on time-saving, manual steps, rolling back to previous versions, time-to-deploy a change.

- [Helm](https://helm.sh/)
- [Kustomize](https://kustomize.io/)
- [ArgoCD](https://issues.redhat.com/browse/PACKIT-1998)
- [Grafana Tanka & Jsonnet](https://blog.codavel.com/declarative-management-of-multiple-kubernetes-clusters-with-tanka-and-jsonnet)
- [Skaffold](https://skaffold.dev/)
- Our current approach

Talk to other teams in our organization and check how they are doing, esp. those working with the SRE team.

**Definition of done**: we have data to make a decision about the way we deploy our services and can make a commitment to change it.

**Comment by lachmanfrantisek** [comment]
Do we want to have a plan (steps for the implementation) prepared as a part of this epic?

**Comment by TomasTomecek** [comment]
> Do we want to have a plan (steps for the implementation) prepared as a part of this epic?

I'd say no so that it's easier to complete.

For me, the outcome of this research is to decide which solution we want to use and then form a plan.

Does that work for you?

**Comment by jpopelka** [comment]
After spending some time creating Helm Charts and Continuous Deployment (CD) for our two cron-jobs ([packit-service-validation](https://github.com/packit/deployment/tree/main/cron-jobs/packit-service-validation#deployment), [import-images](https://github.com/packit/deployment/tree/main/cron-jobs/import-images#deployment)) I have a better understanding of what it is useful for and can better understand the differences between the other technologies.

Helm vs. Kustomize: I went through several comparisons (e.g. [1](https://phoenixnap.com/kb/helm-vs-kustomize), [2 (czech)](https://www.tomaskubica.cz/post/2021/helm-vs-kustomize-co-si-mam-vybrat/)) and none of them look like a better fit four our use-case.
You can actually use a combination of both, which is what most of the articles suggest in the end.
For example, Kustomize can be used as [post-rendering in Helm](https://helm.sh/docs/topics/advanced/). [GitHub runner also contains both tools](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md).

I'd definitely start with Helm and then look at whether adding Kustomize into the process can simplify things for us.

[Tanka & Jsonnet](https://blog.codavel.com/declarative-management-of-multiple-kubernetes-clusters-with-tanka-and-jsonnet) - looks similar to Helm and Kustomize but works with JSONs instead of YAMLs. It has many benefits (jsons are better for machines, yamls are better for people), but to me, it looks like it starts to pay off when you have many applications on many clusters, which is not our case. It's not included in GitHub runner.

[Skaffold (and others)](https://hasura.io/blog/draft-vs-gitkube-vs-helm-vs-ksonnet-vs-metaparticle-vs-skaffold-f5aa9561f948/): I checked only Skaffold and it looks like a newer kid on the block, trying to ease the whole development process (building, tagging and deploying). We can revisit it later once we have Helmized the whole deployment because it can work with Helm as well. It's not included in GitHub runner.

GitHub Actions/workflows vs. ArgoCD: ArgoCD is (as I see it) actually only the last step of the deployment; it's checking a git repo (with Helm Chart for example) and syncs changes to k8s/OpenShift clusters. We can do the same with GHA, just from the other (the git repo) side. So I'd start with implementing the CD with GHA and then later check if adding the ArgoCD would simplify anything for us. (ArgoCD needs additional resources on the cluster, which might be a blocker)

So the steps for our next-gen Continuous Deployment would be:
- Helmize our deployment
  - Create a Helm Chart for secrets - that will be the most interesting part
  - Create a GitHub workflow for installing/upgrading the Helm release (deployed chart instance)
  - Add the rest of the resources to the Helm chart - should be easier
- Research whether Kustomize would help us in any way?
- Research whether ArgoCD would help us in any way?

**Comment by jpopelka** [comment]
Closing, see #419

**Comment by TomasTomecek** [comment]
> works with JSONs instead of YAMLs

lol, not 2022

> I'd start with implementing the CD via GHAs and if we move to MP+, we can research ArgoCD, which is available there.

agreed!

well done with going with helm, based on your research it looks like a right thing to do
